---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: falcon_install
    image_owner: 013907871322
    image_filters:
      - architecture: x86_64
      - name: "suse-sles-15-sp4-v????????-hvm*"
    instance_type: t2.micro
    region: us-west-2
    vpc_subnet_id: subnet-357ed74d
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
