---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: test-instance
    box: ${MOLECULE_DISTRO:-centos/7}
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
